### ISSUE TITLE
Doesn't work in Google Chrome

### ISSUE THREAD

**Issue by alysonsm** [etienne-martin/mapify#3] opened 2015-06-26 12:49 UTC
Searching on the web I found your script and I must say, it is a really nice job of yours. It works perfectly on firefox but I am having some odd behaviours while on google chrome. I tryed many things (looked into your code, changed jquery 'bind' to 'on') to make this works, but with no success.

Here a jsfiddle so you can see it yourself:
http://jsfiddle.net/j1dftnkp/5/

It should change background color when the mouse pointer is on the chest area. I don't know if I missed something.

Can you help me with that?

**Comment by etienne-martin** [comment] 2015-06-26 16:02
Thanks for finding this bug. I'll look into it asap!

**Comment by dcaviness** [comment] 2015-06-26 18:47
This is exactly what I've been looking for. I hope you can get it working in Chrome. Looks to be working in FireFox and IE.

**Comment by etienne-martin** [comment] 2015-06-26 20:07
You need to set the name attribute of your map with the same value as the id. 

My mistake. I've updated the doc and your jsfiddle.

http://jsfiddle.net/j1dftnkp/7/

**Comment by dcaviness** [comment] 2015-06-26 20:11
It doesn't appear that the highlight portion is working in chrome. Even your site http://etiennemartin.ca/mapify/ isn't working correctly in Chrome.

**Comment by etienne-martin** [comment] 2015-06-26 20:16
You are using Chrome (43.0.2357.130) on Windows (8.1) right?

**Comment by dcaviness** [comment] 2015-06-26 20:20
Yes that is correct.

**Comment by etienne-martin** [comment] 2015-06-26 23:26
I'm not able to reproduce the problem with the same config as yours.

Do you have Chrome extensions running in the background?

**Comment by etienne-martin** [comment] 2015-06-26 23:32
Have you tried with another computer with the same OS/browser?

I'm closing the issue until we find a way to reproduce the bug.

Thanks.

**Closed by etienne-martin** 2015-06-26 23:32 UTC

**Comment by dcaviness** [comment] 2015-06-29 15:47
This appears to be more of a Windows 8.1 issue than Chrome. I can get this to work in the latest version of Chrome on different OS and devices, but not in Chrome on Windows 8.1.  Due to this not working, I will have to look for alternative options.

**Comment by etienne-martin** [comment] 2015-06-29 23:09
Can you tell me if it's now working using this modified version? http://etiennemartin.ca/mapify2/

**Comment by dcaviness** [comment] 2015-07-02 16:03
It's still not working for me in chrome. It does work in other browsers.

**Comment by jdomingu** [comment] 2016-01-23 02:28
I'm seeing an issue with Chrome on Windows 7 as well. Chrome seems to support the touch event handlers, which seems to be throwing things off. A workaround is to hardcode touchIsSupported to false on line 57.

**Comment by etienne-martin** [comment] 2016-02-11 19:39
Thanks for the finding [jdomingu](https://github.com/jdomingu). It's now fixed in the latest version.
